apiVersion: apps/v1
kind: Deployment
metadata:
  name: appjava
  labels:
    app: Java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Java
  template:
    metadata:
      labels:
        app: Java
    spec:
      containers:
      - name: ajay996/web
        image: nginx:1.14.2