apiVersion: v1
kind: Service
metadata:
  name: java-service
  labels:
    name: java-service
    app: java-web-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: java-web-app
    app: java-web-app
