name: Build & Deploy Java web app 
on:
  push:
    branches:
    - 'main'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPO : ajay996/web123

jobs:
  CI-Pipeline:
    name: Build CI Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker registry by docker
      run: |
        docker login  "${{ env.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKERHUB_USERNAME }}" -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Result Application Build Image Using docker
      run: |
        docker build -t "${{ env.DOCKER_REPO }}":latest .
        docker tag "${{ env.DOCKER_REPO }}":latest "${{ env.DOCKER_REPO }}":${{ github.sha }}
        docker push  "${{ env.DOCKER_REPO }}":${{ github.sha }}
  
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: '"${{ env.DOCKER_REPO_R }}":${{ github.sha }}'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL,HIGH'

  Deploy:
    name: Deploy Pipeline
    needs: CI-Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy on K8's cluster
      run: kubectl apply -f ./manifest/deployment.yaml